language: minimal
dist: trusty

addons:
  ssh_known_hosts: c4dtsrv1.epfl.ch

stages:
  - build
  - name: deploy
    if: branch = main

jobs:
  include:

    - stage: build
      name: webapp
      language: node_js
      node_js: "10"
      install:
        - npm ci -d
      script:
        - npm run lint
        - npm run build --prod

    - stage: deploy
      name: demo.c4dt.org
      before_deploy:
        - echo "$DEPLOY_SSH_KEY" > "$HOME/.ssh/id_ed25519"
        - chmod 600 "$HOME/.ssh/id_ed25519"
      deploy:
        provider: script
        script: ssh omniledger@c4dtsrv1.epfl.ch bin/update_expl.sh
    - name: NPM
      language: node_js
      node_js: "10"
      script: skip # node_js.script default to `make test`
      before_deploy: echo "//registry.npmjs.org/:_authToken=${DEPLOY_NPM_TOKEN}" > "$HOME/.npmrc"
      deploy:
        provider: script
        script: npm ci && npm version prerelease --preid=p`date +%Y%m%d%H%M%S` && npm publish --tag dev

notifications:
  email: false
